config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students do
    resources :addresses, only: [:new, :show, :create]
  end
  resources :courses
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description, :street, :city, :state, :zip_code
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates_presence_of :name
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student_courses.rb
class StudentCourses < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    @student = Student.find(params[:student_id])
    @address = @student.addresses.create(address_params)
    redirect_to student_path(@address.student)
  end

  private

  def address_params
    params.require(:address).permit(:description, :city, :state, :zip_code, :street, :student_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    redirect_to student_path(@student)
  end

  def show
    @student = Student.find(params[:id])
  end

  def index
    @students = Student.all
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.update(params[:id], student_params)
    redirect_to student_path(@student)
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<%= form_for [@student, @address] do |f| %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.label :street %>
<%= f.text_field :street %>
<%= f.label :city %>
<%= f.text_field :city %>
<%= f.label :state %>
<%= f.text_field :state %>
<%= f.label :zip_code %>
<%= f.text_field :zip_code %>
<%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<%= @course.name %>
<% @course.students.each do |student| %>
<%= student.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <%= link_to "All Students", students_path %>
      <%= link_to "Create New Student", new_student_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<%= form_for @student do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit %>
<% end %>

app/views/students/index.html.erb
<p>Students</p>
<% @students.each do |student| %>
<p><span><%= link_to student.name, student_path(student) %><%= link_to "delete #{student.name}", student_path(student), method: "delete" %></span></p>
<% end %>

app/views/students/new.html.erb
 <%= form_for @student do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.submit %>
 <% end %>

app/views/students/show.html.erb
<h4><%= @student.name %></h4>
<% @student.addresses.each do |address| %>
<%= address.description %>
<%= address.street %>
<%= address.city %>
<%= address.state %>
<%= address.zip_code %>
<% end %>
<% @student.courses.each do |course| %>
<%= course.name %>
<% end %>